apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "ld-demo"
spec:
  stages:
    - name: staging
      sequences:
      - name: release
        tasks:
        - name: flagon
        - name: flagoff
          triggeredAfter: "2m"

