apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.flagon.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"eventName\":\"{{.type}}\",\"value\":\"{{.data.status}}\",\"url\":\
          \"https://rob00334.cloudautomation.live.dynatrace.com/bridge/project/\
          {{.data.project}}/sequence/{{.shkeptncontext}}/stage/{{.data.stage}}\
          \"}'
          https://app.launchdarkly.com/webhook/triggers/{{.env.secret_ld_demoap\
          pfeatureon}}"
      envFrom:
        - name: secret_ld_demoappfeatureon
          secretRef:
            name: ld
            key: demoapp-feature-on
      subscriptionID: a4f797c3-67ca-4479-a739-75277453e56a
      sendFinished: true
    - type: sh.keptn.event.flagoff.triggered
      requests:
        - "curl --header 'Content-Type: application/json' --request POST --data
          '{\"eventName\":\"{{.type}}\",\"value\":\"{{.data.status}}\",\"url\":\
          \"https://rob00334.cloudautomation.live.dynatrace.com/bridge/project/\
          {{.data.project}}/sequence/{{.shkeptncontext}}/stage/{{.data.stage}}\
          \"}'
          https://app.launchdarkly.com/webhook/triggers/{{.env.secret_ld_demoap\
          pfeatureoff}}"
      envFrom:
        - name: secret_ld_demoappfeatureoff
          secretRef:
            name: ld
            key: demoapp-feature-off
      subscriptionID: 5f75b926-d371-45bf-a31d-e85315fc56fd
      sendFinished: true
